export const quotes: {[id: string]: string} = {
  0: '“The world is a book and those who do not travel read only a page.” - Saint Augustine',
  1: '“Not all those who wander are lost.” - j.R.R. Tolkien',
  3: '“Life is either a daring adventure or nothing at all.” - Helen Keller',
  4: '“Take only memories, leave only footprints.” - Chief Seattle',
  5: '“Travel is fatal to prejudice, bigotry, and narrow mindedness, and many of our people need it sorely on these accounts.” - Mark Twain',
  6: '“The real voyage of discovery consists not in seeking new landscapes, but in having new eyes.” - Marcel Proust',
  7: '“Travel makes one modest, you see what a tiny place you occupy in the world.” - Gustave Flaubert',
  8: '“Twenty years from now you will be more disappointed by the things you didn’t do than by the ones you did do.” - H. Jackson Brown Jr.',
  9: '“Never go on trips with anyone you do not love.” - Hemmingway',
  10: '“Like all great travellers, I have seen more than I remember and remember more than I have seen.” - Benjamin Disraeli',
  11: '“Traveling – it leaves you speechless, then turns you into a storyteller.” – Ibn Battuta',
  12: "“If you think adventure is dangerous, try routine, it's lethal.” - Paul Coelho",
  13: '“If you are always trying to be normal, you will never know how amazing you can be.” - Maya Angelou',
  14: '“Stop worrying about the potholes in the road and enjoy the journey.” - Babs Hoffman',
  15: '“Fear is only temporary. Regrets last forever.”',
  16: '“Climb the mountain so you can see the world, not so the world can see you.” - David McCullough',
  17: '“To awaken alone in a strange town is one of the pleasantest sensations in the world.” – Freya Stark',
  18: '“The life you have led doesn’t need to be the only life you have.” – Anna Quindlen',
  19: '“Travel is the only thing you buy that makes you richer.”',
  20: '“Better to see something once than hear about it a thousand times.” – Asian Proverb',
  21: '“We travel not to escape life, but for life not to escape us.”',
  22: '“You don’t have to be rich to travel well.” – Eugene Fodor',
  23: '“Travel is never a matter of money, but of courage.” — Paulo Coelho',
  24: '“Our happiest moments as tourists always seem to come when we stumble upon one thing while in pursuit of something else.” — Lawrence Block',
};
