name: Lint

on:
  push:
    branches:
      - master
      - release/*
  pull_request:

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: yarn install
        run: yarn install

      - name: eslint
        uses: icrawl/action-eslint@v1
