name: Node.js CI

on:
  push:
    branches:
      - master
      - release/*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true
          REACT_APP_API_KEY: 'api-key'
          REACT_APP_AUTH_DOMAIN: 'project-id.firebaseapp.com'
          REACT_APP_DATABASE_URL: 'https://project-id.firebaseio.com'
          REACT_APP_PROJECT_ID: 'project-id'
          REACT_APP_STORAGE_BUCKET: 'project-id.appspot.com'
          REACT_APP_MESSAGING_SENDER_ID: 'sender-id'
          REACT_APP_APP_ID: 'app-id'
          REACT_APP_MEASUREMENT_ID: 'G-measurement-id'
